spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/library}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

node:
  heartbeat-interval: 10s

db:
  dump:
    path: ${DB_DUMP_PATH:./db-dumps/library_dump.sql}
    metadata-path: ${DB_DUMP_METADATA_PATH:./db-dumps/library_dump.meta.json}
    cron: ${DB_DUMP_CRON:0 0 */4 * * *}
    timeout: ${DB_DUMP_TIMEOUT:PT120S}
